# Generated by Django 4.2.7 on 2023-11-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description_short', models.CharField(max_length=300, verbose_name='short description')),
                ('description_long', models.TextField(verbose_name='long description')),
                ('lon', models.FloatField(verbose_name='longitude')),
                ('lat', models.FloatField(verbose_name='latitude')),
            ],
        ),
    ]
