# Generated by Django 4.2.7 on 2023-11-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_image_options_alter_image_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='priority',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
