# Generated by Django 4.2.7 on 2023-11-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_place_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['priority', 'place']},
        ),
        migrations.AlterField(
            model_name='image',
            name='priority',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
